name = "Lynx"
version = "0.1.0"
defaultTargets = ["Lynx", "Erlang", "Lynx.Runner"]
testDriver = "LynxTest"

[[lean_lib]]
name = "Lynx"

[[lean_lib]]
name = "Erlang"
globs = ["Erlang.+"]

[[lean_lib]]
name = "LynxTest"
globs = ["LynxTest.+"]

[[lean_exe]]
name = "Lynx.Runner"
root = "Lynx.Runner"
supportInterpreter = true
