name = "Lynx"
version = "0.1.0"
defaultTargets = ["Lynx", "Lynx.Runner"]
testDriver = "LynxTest"

[[lean_lib]]
name = "Lynx"
globs = ["Lynx", "Lynx.Modules.+"]

[[lean_lib]]
name = "LynxTest"
globs = ["LynxTest.+"]

[[lean_exe]]
name = "Lynx.Runner"
root = "Lynx.Runner"
supportInterpreter = true
